name: Release

on:
  push:
    tags: ["v*"] # solo se dispara al subir un tag que empiece con "v" (ej: v1.0.0)

permissions:
  contents: write # necesario para crear el Release y subir archivos a él

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.47.1"
          channel: "stable"
      - run: flutter pub get
      - run: flutter build apk --release # genera el .apk firmado con la clave de debug (suficiente para portafolio)
      - uses: actions/upload-artifact@v4 # guarda el .apk para que el job final lo recupere
        with:
          name: android-apk # nombre interno del artefacto
          path: build/app/outputs/flutter-apk/app-release.apk

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get update && sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev
        # mismas librerías que instalaste en tu Pop!_OS en el Módulo 1
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.47.1"
          channel: "stable"
      - run: flutter pub get
      - run: flutter config --enable-linux-desktop # habilita el target Linux en este runner
      - run: flutter build linux --release
      - run: tar -czf yes_no_maybe_app-linux.tar.gz -C build/linux/x64/release/bundle .
        # comprime toda la carpeta bundle en un solo archivo descargable
      - uses: actions/upload-artifact@v4
        with:
          name: linux-build
          path: yes_no_maybe_app-linux.tar.gz

  build-windows:
    runs-on: windows-latest # runner con Windows real
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.47.1"
          channel: "stable"
      - run: flutter pub get
      - run: flutter config --enable-windows-desktop
      - run: flutter build windows --release
      - run: Compress-Archive -Path build/windows/x64/runner/Release/* -DestinationPath yes_no_maybe_app-windows.zip
        # Compress-Archive es el comando nativo de PowerShell para zipear (no existe zip en Windows por defecto)
      - uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: yes_no_maybe_app-windows.zip

  create-release:
    needs: [build-android, build-linux, build-windows] # espera a que los 3 builds terminen
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4 # recupera los 3 artefactos subidos arriba
        with:
          path: artifacts # los descarga todos en subcarpetas dentro de "artifacts"

      - uses: softprops/action-gh-release@v2 # crea el Release y adjunta los archivos
        with:
          files: |
            artifacts/android-apk/app-release.apk
            artifacts/linux-build/yes_no_maybe_app-linux.tar.gz
            artifacts/windows-build/yes_no_maybe_app-windows.zip
